### ISSUE TITLE
Failed to load the tab-rename package

### ISSUE THREAD

**Issue by Olmer1st** [PaintScratcher/tab-rename#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Ubuntu 15.10
**Thrown From**: [tab-rename](https://github.com/PaintScratcher/tab-rename) package, v1.2.0
### Stack Trace

Failed to load the tab-rename package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/vadim/.atom/packages/tab-rename/lib/tab-rename-view.coffee:1:1)
    at /home/vadim/.atom/packages/tab-rename/lib/tab-rename-view.coffee:5:3
    at Object.<anonymous> (/home/vadim/.atom/packages/tab-rename/lib/tab-rename-view.coffee:5:3)
    at Object.<anonymous> (/home/vadim/.atom/packages/tab-rename/lib/tab-rename-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vadim/.atom/packages/tab-rename/lib/tab-rename.coffee:1:17)
    at Object.<anonymous> (/home/vadim/.atom/packages/tab-rename/lib/tab-rename.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:661:34)
    at /usr/share/atom/resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:511:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -1:34.5.0 tabs:keep-preview-tab (div.title.temp)
     -1:08.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/mnt/Data/Projects",
    "disabledPackages": [
      "vim-mode",
      "minimap"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
angularjs, v0.3.3
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-ternjs, v0.8.7
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v0.10.4
color-picker, v2.0.13
data-atom, v0.17.1
emmet, v2.3.14
file-icons, v1.6.12
highlight-line, v0.11.0
javascript-object-snippets, v0.3.0
javascript-snippets, v1.0.0
js-refactor, v0.6.0
jsformat, v0.9.0
language-mongodb, v0.3.1
linter, v1.11.2
linter-csslint, v1.1.0
node-debugger, v1.1.9
nodejs-snippets, v1.1.0
php-debug, v0.1.4
pretty-json, v0.4.1
python-autopep8, v0.1.3
python-tools, v0.6.7
refactor, v0.6.0
rest-client, v0.5.0
tab-rename, v1.2.0
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Comment by omi10859** [comment]
same issue

**Comment by SonGokuPetit** [comment]
Come on!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SonGokuPetit** [comment]
thanks ;-)
